(require 'string)
(require 'list)
(require 'comments)

(defun header-insert ()
  "print 3 lines"
  (interactive)
  (comments-insert-bar)
  (comments-insert-empty-line)
  (setq fill0 "/*                                                        ::::::::            */\n/*   ")
  (insert fill0)
  (setq fname (buffer-name))
  (insert fname)
  (setq fill1 (substring "                                                   :+:    :+:            */\n/*                                                     +:+                    */\n/*   By: " (length fname)))
  (insert fill1)
  (setq user (getenv "USER"))
  (setq mail (getenv "MAIL"))
  (if (string= mail nil)
	(setq mail "marvin@codam.nl"))
  (insert user " <" mail ">")
  (setq fill2 (substring "                                          +#+                     */\n/*                                                   +#+                      */\n/*   Created: " (+ (length user) (length mail))))
  (insert fill2)
  (setq createdate (format-time-string "%Y/%m/%d %T"))
  (insert createdate " by " user)
  (setq fill3 (substring "              #+#    #+#                 */\n/*   Updated: " (length user)))
  (insert fill3)
  (setq updatedate (format-time-string "%Y/%m/%d %T"))
  (insert updatedate " by " user)
  (setq fill4 (substring "              ########   odam.nl         */\n" (length user)))
  (insert fill4)
  (comments-insert-empty-line)
  (comments-insert-bar))

(defun update ()
  "update update line"
  (interactive)
  (if buffer-modified-p
	(setq goto-char (663))
	(setq set-mark-command)
	(setq goto-char (682))
	(setq delete-region)
	(insert updatedate)))
(provide 'header-insert)
